# Uncomment this line to define a global platform for your project
platform :ios, '8.4'


source 'https://github.com/CocoaPods/Specs.git'

project 'Example.xcodeproj'

target 'Example' do
	pod 'keytechkit', :path =>'../'
end

target 'ExampleTests' do
	pod 'keytechkit', :path =>'../'
end
