language: objective-c
osx_image: xcode7.3
xcode_workspace: Example/Example.xcworkspace
xcode_scheme: Example
xcode_sdk: iphonesimulator9.2

podfile: Example/Podfile

before_install:
 - gem install cocoapods
 - pod repo update
